#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch_name=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch_name" = "main" ]; then
  echo "[Husky] Direct commits to 'main' are blocked. Please create a feature branch and open a PR."
  exit 1
fi

# Staged files run through lint-staged (prettier)
npx --no -- lint-staged

# Lint and Type-check
npm run lint
npm run type-check
